### ISSUE TITLE
Bot restarting

### ISSUE THREAD

**Issue by Spiderjockey02** [WearifulCupid0/erela.js-deezer#2]
when i use this plugin and I enter a facebook link. It errors out and causes my bot to restart. So I think the problem is that it tries to search deezer with my facebook link because when i remove this plugin it returns with a normal error message instead of crashing
![image](https://user-images.githubusercontent.com/55885015/107802421-35f99c80-6d59-11eb-83d4-217ab4da9763.png)
.

**Comment by WearifulCupid0** [comment]
Are you using other erela.js Plugin?
Like erela.js-spotify

**Comment by Spiderjockey02** [comment]
Yh sorry you can delete this issue as I was misformed and it has nothing to do with this plugin.
