### ISSUE TITLE
Playlists not working

### ISSUE THREAD

**Issue by Spiderjockey02** [WearifulCupid0/erela.js-deezer#3]
it seems that only the first song from the playlists load.
![image](https://user-images.githubusercontent.com/55885015/107886317-f1a40300-6ef6-11eb-8dae-0b15b2bcca09.png)
I can load playlists on youtube/spotify so it's not an issue with erela itself (well i think)

**Comment by Spiderjockey02** [comment]
it appears to be albums aswell. (im using the example links in README.md)

**Comment by WearifulCupid0** [comment]
Thanks for your Issue :)
I'm going do resolve this error.
